name: Release

on:
  workflow_run:
    workflows: ['Run Tests']
    types: [completed]
    branches:
      - 'main'

permissions:
  contents: write
  actions: write

jobs:
  tag_release:
    name: 'Release - Tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Configure git authentication
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/modularis-dev/modularis-core.git
      - name: Release - Add Tag
        run: |
          RELEASE_VERSION="$(npx git-conventional-commits version)"
          RELEASE_CHANGELOG="$(npx git-conventional-commits changelog)"
          git tag -a "v$RELEASE_VERSION" -m "$RELEASE_CHANGELOG"
          git push origin "v$RELEASE_VERSION"
