name: Run Tests
 
on: [push]
 
jobs:
  test_execution:
    name: Test - Execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup - Environment
        uses: ./.github/actions/setup

      - name: Test Code Execution
        run: php artisan test
  test_style:
    name: Test - Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup - Environment
        uses: ./.github/actions/setup

      - name: Test Code Style
        run: vendor/bin/pint --test
  test_quality:
    name: Test - Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup - Environment
        uses: ./.github/actions/setup

      - name: Test Code Quality
        run: vendor/bin/phpstan analyse
